#!/usr/bin/python3
from selenium import webdriver
from time import sleep
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

def FastFinger():
    service = Service(ChromeDriverManager().install())
    chrome_options = Options()
    chrome_options.add_argument('--ignore-certificate-errors-spki-list')
    chrome_options.add_argument(f"--user-data-dir=C:\\Users\\bezie\\AppData\\Local\\Google\\Chrome\\User Data\\Default")
    chrome_options.add_argument('log-level=3')
    driver = webdriver.Chrome(service=service, options=chrome_options)
    driver.get("https://10fastfingers.com/typing-test")
    driver.set_page_load_timeout(30)

    driver.maximize_window()
    sleep(4)
    Words = driver.find_elements(By.XPATH, "//div[@id='row1']/span")
    Words = [i.text for i in Words]
    temp = [""] * len(Words)
    lenDone = 0
    InputField = driver.find_element(By.ID, "inputfield")
    for elem in Words:
        if (elem != ''):
            InputField.send_keys(elem + " ")
        elif (temp[lenDone] == ''):
            temp = driver.find_elements(By.XPATH, "//div[@id='row1']/span")
            temp = [i.text for i in temp]
            InputField.send_keys(temp[lenDone] + " ")
        else:
            InputField.send_keys(temp[lenDone] + " ")
        lenDone += 1
    sleep(1000)

def main():
    FastFinger()

main()